import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { execa } from "execa";

export class Reporter {
    /**
     * Generates a markdown report of the quality check results.
     * @param {Array<Object>} results - The results of the checkers.
     */
    async generateReport(results) {
        try {
            const { stdout } = await execa("git", ["rev-parse", "--show-toplevel"]);
            const root = stdout.trim();
            const reportPath = join(root, "quality-report.md");

            let content = "# 🚨 Quality Check Report\n\n";
            content += `Generated on: ${new Date().toLocaleString()}\n\n`;
            content += "## 📉 Results\n\n";
            content += "| Checker | Status | Message |\n";
            content += "| :--- | :--- | :--- |\n";

            results.forEach((r) => {
                const status = r.success ? "✅ Pass" : "❌ Fail";
                content += `| ${r.name} | ${status} | ${r.message} |\n`;
            });

            const failures = results.filter((r) => !r.success);
            const setupSuggestions = results.filter((r) => r.success && r.suggestedFix);

            if (failures.length > 0) {
                content += "\n## 🛠 How to fix\n\n";
                failures.forEach((f) => {
                    content += `### ${f.name}\n`;
                    if (f.details) {
                        content += f.details + "\n\n";
                    } else if (f.suggestedFix) {
                        content += `- Run: \`${f.suggestedFix}\` to fix.\n`;
                    } else if (f.name.includes("Test")) {
                        content += `- Run: \`npm test\` to see test errors.\n`;
                    } else if (f.name.includes("Linting")) {
                        content += "- Run: \`npm run lint --fix\` or \`npm run lint:fix\` to fix.\n";
                    } else if (f.name.includes("Formatting")) {
                        content += "- Run: \`npm run format\` to fix formatting.\n";
                    } else if (f.name.includes("Commit Message")) {
                        content += "- Use format: \`feat: add feature\` or \`:emoji: message\`\n";
                    } else if (f.name.includes("Secret")) {
                        content += "- Remove secrets from files or add \`// cqc-disable secret\` comment.\n";
                    } else if (f.name.includes("Vulnerabilities")) {
                        content += "- Run: \`npm audit fix\` to fix vulnerabilities.\n";
                    }
                    content += "\n";
                });
            }

            if (setupSuggestions.length > 0) {
                content += "\n## 💡 Setup Suggestions\n\n";
                setupSuggestions.forEach((s) => {
                    content += `### ${s.name}\n- ${s.message}\n- Run: \`${s.suggestedFix}\` to install necessary dependencies.\n\n`;
                });
            } else if (failures.length === 0) {
                content += "\n## ✅ Results\n\nNo failures detected.";
            }

            content += "\n---\n*This report is automatically generated by commit-quality-check.*";

            await writeFile(reportPath, content, "utf8");
            return reportPath;
        } catch (error) {
            throw new Error(`Failed to generate report: ${error.message}`);
        }
    }
}