import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { execa } from "execa";

export class Reporter {
  async generateReport(results, options = {}) {
    try {
      const root = options.root || await this.getProjectRoot();
      const reportPath = join(root, "quality-report.md");
      const content = this.buildReportContent(results, options);

      await writeFile(reportPath, content, "utf8");
      return reportPath;
    } catch (error) {
      throw new Error(`Failed to generate report: ${error.message}`);
    }
  }

  async getProjectRoot() {
    const { stdout } = await execa("git", ["rev-parse", "--show-toplevel"]);
    return stdout.trim();
  }

  buildReportContent(results, options = {}) {
    const failures = results.filter((result) => !result.success);
    const setupSuggestions = results.filter((result) => result.success && result.suggestedFix);
    const generatedAt = new Date().toLocaleString();

    let content = "# Quality Check Report\n\n";
    content += `Generated on: ${generatedAt}\n\n`;
    content += this.buildSummarySection(results, failures);
    content += this.buildSuggestionSection(options.suggestionSummary);
    content += this.buildAnalysisSection(options.analysis);
    content += this.buildScoreSection(options.scoreSummary);
    content += this.buildResultsTable(results);

    if (failures.length > 0) {
      content += this.buildActionPlanSection(failures);
      content += this.buildFailureDetailsSection(failures);
    } else {
      content += "## Result\n\n";
      content += "All active quality checks passed. You can retry your commit.\n\n";
    }

    if (setupSuggestions.length > 0) {
      content += this.buildSetupSuggestionsSection(setupSuggestions);
    }

    content += "---\n";
    content += "*This report is automatically generated by CommitIQ Engine.*\n";
    return content;
  }

  buildAnalysisSection(analysis) {
    if (!analysis) {
      return "";
    }

    let content = "## Diff Analysis\n\n";
    content += `- Staged files: ${analysis.files.length}\n`;

    if (analysis.lineStats) {
      content += `- Added lines: ${analysis.lineStats.added}\n`;
      content += `- Removed lines: ${analysis.lineStats.removed}\n`;
    }

    if (analysis.deletedTestFiles?.length > 0) {
      content += `- Deleted test files: ${analysis.deletedTestFiles.length}\n`;
    }

    if (analysis.removedTestLines?.length > 0) {
      content += `- Removed test lines: ${analysis.removedTestLines.length}\n`;
    }

    if (analysis.workspaceScopes?.length > 0) {
      content += `- Workspace scopes: ${analysis.workspaceScopes.join(", ")}\n`;
    }

    if (analysis.topLevelAreas?.length > 0) {
      content += `- Top-level areas: ${analysis.topLevelAreas.join(", ")}\n`;
    }

    const signalLabels = [];
    if (analysis.signals?.touchesAuth) signalLabels.push("auth");
    if (analysis.signals?.touchesCI) signalLabels.push("ci");
    if (analysis.signals?.touchesDependencies) signalLabels.push("dependencies");
    if (analysis.signals?.touchesEnv) signalLabels.push("env");
    if (analysis.signals?.touchesMigrations) signalLabels.push("migrations");
    if (analysis.signals?.removesTests) signalLabels.push("removes-tests");

    if (signalLabels.length > 0) {
      content += `- Signals: ${signalLabels.join(", ")}\n`;
    }

    content += "\n";
    return content;
  }

  buildScoreSection(scoreSummary) {
    if (!scoreSummary) {
      return "";
    }

    let content = "## Commit Quality Score\n\n";
    content += `- Probable type: \`${scoreSummary.probableType}\`\n`;
    content += `- Probable scope: \`${scoreSummary.probableScope}\`\n`;
    content += `- Atomicity: ${scoreSummary.atomicity}\n`;
    content += `- Scope precision: ${scoreSummary.scopePrecision}\n`;
    content += `- Test coverage signal: ${scoreSummary.testCoverage} (${scoreSummary.testsStatus})\n`;
    content += `- Risk: ${scoreSummary.riskLevel} (${scoreSummary.riskScore}/100)\n`;
    content += `- Global score: ${scoreSummary.globalScore}/100\n`;

    if (scoreSummary.reasons.length > 0) {
      content += "- Risk reasons:\n";
      scoreSummary.reasons.forEach((reason) => {
        content += `  - ${reason}\n`;
      });
    }

    content += "\n";
    return content;
  }

  buildSuggestionSection(suggestionSummary) {
    if (!suggestionSummary) {
      return "";
    }

    let content = "## Suggested Commit\n\n";
    content += `- Header: \`${suggestionSummary.suggestedHeader}\`\n`;

    if (suggestionSummary.rationale.length > 0) {
      content += "- Why:\n";
      suggestionSummary.rationale.forEach((reason) => {
        content += `  - ${reason}\n`;
      });
    }

    content += "\n";
    return content;
  }

  buildSummarySection(results, failures) {
    const passedCount = results.length - failures.length;

    let content = "## Summary\n\n";
    content += `- Total checks: ${results.length}\n`;
    content += `- Passed: ${passedCount}\n`;
    content += `- Failed: ${failures.length}\n`;

    if (failures.length > 0) {
      const failedNames = failures.map((failure) => `\`${failure.name}\``).join(", ");
      content += `- Blockers: ${failedNames}\n\n`;
      content += "Commit blocked. Fix failed checks below, then run your commit again.\n\n";
    } else {
      content += "\nNo blockers detected.\n\n";
    }

    return content;
  }

  buildResultsTable(results) {
    let content = "## Results\n\n";
    content += "| Checker | Status | Message |\n";
    content += "| :--- | :--- | :--- |\n";

    results.forEach((result) => {
      const status = result.success ? "PASS" : "FAIL";
      content += `| ${result.name} | ${status} | ${result.message} |\n`;
    });

    content += "\n";
    return content;
  }

  buildActionPlanSection(failures) {
    let content = "## What To Do Next\n\n";
    content += "Work through these steps in order:\n\n";

    failures.forEach((failure, index) => {
      content += `${index + 1}. ${this.getActionSummary(failure)}\n`;
    });

    content += `\n${failures.length + 1}. Retry your commit after fixes are applied.\n\n`;
    return content;
  }

  buildFailureDetailsSection(failures) {
    let content = "## Fix Details\n\n";

    failures.forEach((failure) => {
      content += `### ${failure.name}\n\n`;
      content += `Problem: ${failure.message}\n\n`;

      const commands = this.getRecommendedCommands(failure);
      if (commands.length > 0) {
        content += "Recommended command(s):\n\n";
        commands.forEach((command) => {
          content += `- \`${command}\`\n`;
        });
        content += "\n";
      }

      const guidance = this.getGuidance(failure);
      if (guidance.length > 0) {
        content += "How to fix:\n\n";
        guidance.forEach((step) => {
          content += `- ${step}\n`;
        });
        content += "\n";
      }

      if (failure.details) {
        content += "Technical details:\n\n";
        content += "```text\n";
        content += `${failure.details}\n`;
        content += "```\n\n";
      }
    });

    return content;
  }

  buildSetupSuggestionsSection(setupSuggestions) {
    let content = "## Optional Setup Suggestions\n\n";
    content += "These checks were skipped because the related tool is missing. Install them if you want stronger guardrails.\n\n";

    setupSuggestions.forEach((suggestion) => {
      content += `### ${suggestion.name}\n\n`;
      content += `Current status: ${suggestion.message}\n\n`;
      if (suggestion.suggestedFix) {
        content += "Install with:\n\n";
        content += `- \`${suggestion.suggestedFix}\`\n\n`;
      }
    });

    return content;
  }

  getActionSummary(failure) {
    if (failure.suggestedFix) {
      return `${failure.name}: run \`${failure.suggestedFix}\` and resolve any reported errors.`;
    }

    if (failure.name.includes("Commit Message")) {
      return "Commit Message Quality: rewrite the commit message to match Conventional Commits or Gitmoji.";
    }

    if (failure.name.includes("Secret")) {
      return "Secret Scanner: remove or mask the secret before retrying the commit.";
    }

    return `${failure.name}: inspect the details below and apply the suggested fix.`;
  }

  getRecommendedCommands(failure) {
    if (failure.suggestedFix) {
      return [failure.suggestedFix.replace(/^Run:\s*/i, "")];
    }

    if (failure.name.includes("Linting")) {
      return ["npm run lint --fix", "npm run lint:fix"];
    }

    if (failure.name.includes("Formatting")) {
      return ["npm run format"];
    }

    if (failure.name.includes("Test")) {
      return ["npm test"];
    }

    if (failure.name.includes("Vulnerabilities")) {
      return ["npm audit fix"];
    }

    if (failure.name.includes("NPM Pack")) {
      return ["npm pack --dry-run"];
    }

    return [];
  }

  getGuidance(failure) {
    if (failure.name.includes("Linting")) {
      return [
        "Run the lint command to see the full list of violations.",
        "Apply auto-fixes when available, then review remaining manual issues.",
        "Restage the updated files before committing again.",
      ];
    }

    if (failure.name.includes("Formatting")) {
      return [
        "Run the formatter on the files reported below.",
        "Review the diff if formatting changed file structure or generated snapshots.",
        "Restage the formatted files before retrying the commit.",
      ];
    }

    if (failure.name.includes("Commit Message")) {
      return [
        "Use a message like `feat(auth): add login` or `:art: update readme`.",
        "Avoid plain version numbers or empty commit message files.",
      ];
    }

    if (failure.name.includes("Secret")) {
      return [
        "Remove the secret from the staged content, not only from the working file.",
        "Rotate any credential that may already be exposed.",
        "If the match is intentional, add `// cq-disable secret` on that line.",
      ];
    }

    if (failure.name.includes("Debug Artifacts")) {
      return [
        "Remove `console.log` and `debugger` from staged script files.",
        "If a debug line must stay intentionally, annotate that line with `// cq-disable debug`.",
      ];
    }

    if (failure.name.includes("Vulnerabilities")) {
      return [
        "Run the audit fix command first.",
        "If some vulnerabilities remain, inspect the dependency tree and upgrade packages manually.",
      ];
    }

    if (failure.name.includes("Type Check")) {
      return [
        "Run the typecheck script locally to see the full compiler output.",
        "Fix type errors, then rerun the same script before committing again.",
      ];
    }

    if (failure.name.includes("Test")) {
      return [
        "Run the test command locally to inspect the full failing output.",
        "Fix the failing test or the underlying code regression.",
        "Rerun the test command before retrying the commit.",
      ];
    }

    if (failure.name === "Build") {
      return [
        "Run the build script locally and fix the first compilation error.",
        "Retry once the project builds successfully from a clean state.",
      ];
    }

    if (failure.name.includes("NPM Pack")) {
      return [
        "Run `npm pack --dry-run` manually to inspect which file or metadata is invalid.",
        "Check `files`, `main`, `exports`, and `bin` entries in `package.json`.",
      ];
    }

    if (failure.name.includes("Playwright")) {
      return [
        "Run the e2e script locally to inspect the browser-level failure.",
        "Fix the failing scenario, then rerun the same e2e command.",
      ];
    }

    return ["Review the technical details below and apply the suggested fix."];
  }
}
